kind: pipeline
type: docker

name: umls-search-server

steps:
  - name: copy data
    image: apline
    environment:
        MMLITE_DATA_PATH:
          from_secret: mmlite_data_path
    commands:
      - cp ${MMLITE_DATA_PATH} server
  - name: build
    image: maven:3.9.2-eclipse-temurin-17-alpine
    environment:
      MMLITE_JAR_PATH:
        from_secret: mmlite_jar_path
    commands:
      - mvn install:install-file \
         -Dfile= \
         -DgroupId=gov.nih.nlm.nls \
         -DartifactId=metamaplite \
         -Dversion=3.6.2rc8 \
         -Dpackaging=jar \
         -DgeneratePom=true
      - mvn install

  - name: run
    image: eclipse-temurin:17
    ports:
      - 1313
    environment:
      SERVER_PORT: 1313
      DB_HOST: localhost
      DB_NAME:
        from_secret: database_name
      DB_USERNAME:
        from_secret: database_username
      DB_PASSWORD:
        from_secret: database_password
    commands:
      - java -jar server/target/umls-search-0.1.0.jar

trigger:
  branch:
  - production
