kind: pipeline
type: docker
name: umls-search-server

steps:
  - name: build
    image: maven:3.9.2-eclipse-temurin-17-alpine
    volumes:
      - name: metamaplite_data
        path: /tmp/metamaplite
      - name: metamaplite_jar
        path: /tmp/metamaplite.jar
    environment:
      MMLITE_DIR: /tmp/metamaplite
    commands:
      - mvn install:install-file \
         -Dfile=/tmp/metamaplite.jar \
         -DgroupId=gov.nih.nlm.nls \
         -DartifactId=metamaplite \
         -Dversion=3.6.2rc8 \
         -Dpackaging=jar \
         -DgeneratePom=true

  - name: run
    image: eclipse-temurin:17
    ports:
      - 1313
    environment:
      SERVER_PORT: 1313
      DB_HOST: localhost
      DB_NAME:
        from_secret: database_name
      DB_USERNAME:
        from_secret: database_username
      DB_PASSWORD:
        from_secret: database_password
    commands:
      - java -jar server/target/umls-search-0.1.0.jar

volumes:
  - name: metamaplite_data
    host:
      path: /home/ncuuser/ci/metamaplite
  - name: metamaplite_jar
    host:
      path: /home/ncuuser/ci/metamaplite-3.6.2rc8-standalone.jar

trigger:
  branch:
  - production
