kind: pipeline
type: docker
name: umls-search-server

steps:
  - name: build
    image: bluebetweenneck/umlssearch
    ports:
      - 1313
    environment:
      SERVER_PORT: 1313
      DB_HOST: localhost
      DB_NAME:
        from_secret: database_name
      DB_USERNAME:
        from_secret: database_username
      DB_PASSWORD:
        from_secret: database_password
    settings:
      mmlite_data_path:
        from_secret: mmlite_data_path
      mmlite_jar_path: 
        from_secret: mmlite_jar_path

trigger:
  branch:
  - production
