kind: pipeline
type: docker
name: umls-search-server

steps:
  - name: build
    image: maven:3.9.2-eclipse-temurin-17-alpine
    volumes:
      - name: metamaplite_jar
        path: /tmp/metamaplite.jar
      - name: metamaplite_data
        path: /tmp/metamaplite
      - name: target_jar_path
        path: /var/umls-search
    environment:
      MMLITE_DIR: /tmp/metamaplite
    commands:
      - mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=/tmp/metamaplite.jar
      - mvn -f server/pom.xml install \
            -Pci \
            -Ddir=/var/umls-search \
            -DfinalName=server

volumes:
  - name: metamaplite_data
    host:
      path: /home/ncuuser/ci/metamaplite
  - name: metamaplite_jar
    host:
      path: /home/ncuuser/ci/metamaplite-3.6.2rc8-standalone.jar
  - name: target_jar_path
    host:
      path: /home/ncuuser/deploy/umls-search

trigger:
  branch:
  - production

