kind: pipeline
type: docker
name: umls-search-server

steps:
  - name: build
    image: bluebetweenneck/mvnbuildboot
    environment:
      MMLITE_DATA_PATH:
        from_secret: mmlite_data_path
      MMLITE_JAR_PATH:
        from_secret: mmlite_jar_path
    settings:
      mmlite_data_path: mmlite_data_path
      mmlite_jar_path: mmlite_jar_path

  - name: run
    image: eclipse-temurin:17
    ports:
      - 1313
    environment:
      SERVER_PORT: 1313
      DB_HOST: localhost
      DB_NAME:
        from_secret: database_name
      DB_USERNAME:
        from_secret: database_username
      DB_PASSWORD:
        from_secret: database_password
    commands:
      - java -jar server/target/umls-search-0.1.0.jar

trigger:
  branch:
  - production
